### ISSUE TITLE
Roll out a new release

### ISSUE THREAD

**Issue by rambo** [jerry73204/realsense-rust#10]
One should get #2, #5 and #8 when installing a numbered version.

Tag a new version and do whatever else crates.io needs to pick it up.

**Comment by jerry73204** [comment]
Now 0.3.2 is ready.
Also you can use the git repo directly for development purpose.

```toml
realsense-rust = { git = "https://github.com/jerry73204/realsense-rust.git" }
```

**Comment by rambo** [comment]
thanks, I use my fork for development (I tag versions by date there). I'll try to get around testing the new version as soon as possible but I'm busy this week and away the next so this will take a while...
