### ISSUE TITLE
Project status and next steps

### ISSUE THREAD

**Issue by ed-aka-yaboi** [jerry73204/realsense-rust#11]
Is this still under development? Which bits are ready for production use? What would be the next steps to moving it towards being production ready? How can I get involved?

**Comment by jerry73204** [comment]
This crate was developed by the time I was developing the [hacky-arm](https://github.com/jerry73204/hacky-arm) project. That is the only near-production usage I know so far. I moved on my focus on later projects so the crate is updated occasionally. If you would like to help, we can consider promote others as the maintainer.

The next step would to make it feature complete. Better to get started by replicating the [examples](https://github.com/IntelRealSense/librealsense/tree/master/examples) from official repo.

**Comment by jerry73204** [comment]
The repo is no longer maintained and moves to Tangram Visions's Gitlab.

https://gitlab.com/tangram-vision-oss/realsense-rust
