### ISSUE TITLE
capture_images_async example panics + does not compile as is

### ISSUE THREAD

**Issue by ed-aka-yaboi** [jerry73204/realsense-rust#13]
cargo.toml file is as follows:

```
[package]
name = "test"
version = "0.1.0"
authors = ["author <author@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realsense-rust = {version = "0.3.2", features = ["image", "nalgebra"]}
```

I have also tried:

```
[dependencies]
realsense-rust = {version = "0.3.2", features = ["with-image", "with-nalgebra"]}
```

Each time I get

```
thread 'main' panicked at 'please enable with-image and with-nalgebra features to run this example', src/main.rs:158:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

To get to this point I deleted the top line
```
use anyhow::Result;
```

as when I had it included I received the following complaint from clippy:

```
error[E0432]: unresolved import `anyhow`
 --> src/main.rs:2:5
  |
2 | use anyhow::Result;
  |     ^^^^^^ use of undeclared type or module `anyhow`

```

@jerry73204 could you please advise on a fix

**Comment by jerry73204** [comment]
I guess you tried to run the examples by copying [example source](https://github.com/jerry73204/realsense-rust/blob/master/examples/capture_images.rs) to your own crate.

Running examples can be as easy as the following. There is no need of copying. The `with-{image,nalgebra}` features are enabled by default.
```sh
cargo run --release --example capture_images
```

If you would like to take the example as template, I suggest starting from the [pose example](https://github.com/jerry73204/realsense-rust/blob/master/examples/pose.rs). It's easier to approach. For the more complex capture\_image example, you can copy the source inside the mod ([link](https://github.com/jerry73204/realsense-rust/blob/0a3102747d1b75861bb2eea4d2cf4bb25a03e197/examples/capture_images.rs#L5-L149)) to your main.rs. Also, copy the dev-dependencies ([link](https://github.com/jerry73204/realsense-rust/blob/0a3102747d1b75861bb2eea4d2cf4bb25a03e197/Cargo.toml#L22-L26)) to your Cargo.toml.

**Comment by jerry73204** [comment]
Closing this issue. Feel free to re-open it you with to continue.
