### ISSUE TITLE
A question regarding how to extend functionality

### ISSUE THREAD

**Issue by neilyoung** [jerry73204/realsense-rust#16]
Hi Jerry, thanks for your efforts and thanks for sharing the results. As a beginner with Rust (but not a beginner with RS), I'm going to port an existing python app to Rust. I was able to include and use your existing realsense-rust crate as of 0.4.

My python code makes use of functions like:

```
device = config.resolve(self.__pipeline).get_device()
device.get_info(rs.camera_info.firmware_version))
device.get_info(rs.camera_info.serial_number

self.__pose_sensor = device.first_pose_sensor()
self.__pose_sensor.set_option(rs.option.enable_map_preservation, 1)
sensor.set_notifications_callback(self.__callback)


```

Unfortunately I can't figure out, how achieve something similar with your lib. Would you mind to give me a pointer?

**Comment by neilyoung** [comment]
I'm especially missing a way to provide the second parameter for this C function in `config.rs`:

```
 pub fn rs2_config_resolve(
        config: *mut rs2_config,
        pipe: *mut rs2_pipeline,
        error: *mut *mut rs2_error,
    ) -> *mut rs2_pipeline_profile;

```

Any help appreciated.

**Comment by neilyoung** [comment]
Anybody?

**Comment by neilyoung** [comment]
OK, disregard. Found something different.  https://gitlab.com/aivero/public/librealsense-rs. Pretty incomplete, but easy to extend. Seems simpler knitted and more like the original SDK

**Comment by jerry73204** [comment]
Sorry I cannot give quick response due to daytime errands.

The `set_notifications_callback` is not implemented yet. I would try to implement it if I have time. Before that happens, I make `from_raw/into_raw` methods public in master branch. You can obtain the raw pointers and pass to [realsense-sys](https://docs.rs/realsense-sys/) to call the raw C API.

You can change Cargo.toml use the master branch.

```toml
realsense-rust = { git = "https://github.com/jerry73204/realsense-rust.git" }
```

To generate the document from source,

```rust
cargo doc --open
```

**Comment by jerry73204** [comment]
If you have hard time understanding the API, your comment would be appreciated to help me see the shortcomings.

**Comment by neilyoung** [comment]
Don't worry, it is me, who is not getting it :). I'm a Rust beginner, and a lot of your code ist pretty much unreadable for me. In contrary the quoted code, which might not be that elegant, but follows more directly the C++ SDK (as it seems to me) is by that way more readable. Seems, there were also not that experienced programmers at work or they didn't want to prove witch every line, how clever they are :) (I don't say you did it, don't get me wrong).

Especially with the `config.resolve` function. In your code there is (at least for me) no way to have access to the required `*mut rs2_pipeline`, because the required handle is behind the private `ptr` in `pipeline`.  And to provide a "getter" for thsi seemed somehow unclean to me. The different encapsulation might work for most of the functions, but for such breakouts, which need to have access to other struct instances "over" the borders away, it doesn't work. 

Also there is something strange with your lib. It happened to me 100% that the "destructor" was not called if terminating the app from e.g. the debugger. So the next attempt failed with "T.265 already running". I always had to unplug/replug USB to get it to work again. 

Anyway, it is just me, don't bother. 

I will check the from_raw/into_raw and see, if it helps me.

Thanks

**Comment by jerry73204** [comment]
Your guess is correct. The API was more like C++ rather than pyrealsense. It is similar to C++ but with more safety guarantees. An illustrating example is the [Pipeline](https://docs.rs/realsense-rust/0.4.0/realsense_rust/pipeline/struct.Pipeline.html) API. It is designed to prevent users from calling `stop()` twice in compile time. However, the C++ cannot stop you from doing so and raises an exception.

I see the the API is a bit "low-level", just like Intel's C++ SDK. I think it's not the cleverness about the design, but the C++ and Python sides have different considerations based on the choice of language. Writing C++ is unlike Python. We have to take care of every manually allocated memory. The lists and dicts are not free in C++, so we cannot provide a method consuming and returning lists without considering memory safety.

The realsense-rust, which uses much unsafe code to port C++ API, also suffers the burden. I recently reflect on this. It could have more convenient things (like pyrealsense's Device), more comprehensive namings (e.g. `Frame<marker::Video>` -> `VideoFrame`),  and more documented. Maybe it will happen in the next version.

Besides, please open an issue that it does not terminate the device properly.

**Comment by neilyoung** [comment]
OK, I tried your master version, but I'm appearing problems (might again be Rust basic knowledge): After trying to obtain the raw handles I'm no longer allowed to use the `pipeline`, since it has been moved (use of moved value: `pipeline`


```
value used here after moverustc(E0382)
main.rs(43, 26): `pipeline` moved due to this method call
main.rs(39, 9): move occurs because `pipeline` has type)

```


![image](https://user-images.githubusercontent.com/731020/98790500-1bcfbb80-2404-11eb-9b36-c73dd8197968.png)

**Comment by jerry73204** [comment]
It's due to ownership rules in Rust. The `Pipeline::into_raw_pars` consumes the instance into raw pointers, moving the ownership of pipeline away, so you cannot use it later. Ownership is a fundamental concept in Rust and I suggest the [reading](https://depth-first.com/articles/2020/01/27/rust-ownership-by-example/).

The correct way is done as the following.
1. Unpack the pipeline to raw pointers by `pipeline.into_raw_parts()`.
2. Do whatever you want with realsense-sys.
3. Recover the pipeline back by `Pipeline::from_raw_parts()`.

Note that the function signature of `from/into_raw_parts` depends on the pipeline state. The pipeline can switch from inactive to active state and vice versa by `start()` and `stop()` methods. Look at my generated doc to see the details. ([InactivePipeline](https://imgur.com/FmVabfe), [ActivePipeline](https://imgur.com/RqL7YPr))

This is the minimal example I can think of (not tested).

```rust
use realsense_rust::InactivePipeline;
let pipeline = InactivePipeline::new();
let (pipe_ptr, context_ptr) = pipeline.into_raw_parts(); // unpack the pipeline

// do some dirty job here
// before from_raw_parts, accessing pipeline variable is invalid here.

// recover the pipeline. The unsafe {} block is mandatory
let pipeline = unsafe { InactivePipeline::from_raw_parts(pipe_ptr, context_ptr) };
```

**Comment by neilyoung** [comment]
OK, that works. Thanks for the elaboration. But it all looks very complicated and - forgive me - pretty insane to me (even though it might be the safest code on earth). Maybe I'm to old for this sh*t... There is still a riddle, how to call things like that from that point:

```
pub fn rs2_config_resolve(
        config: *mut rs2_config,
        pipe: *mut rs2_pipeline,
        error: *mut *mut rs2_error,
    ) -> *mut rs2_pipeline_profile;

```

I appreciate your efforts, but I think I rather stick with the other code, or with Python, which works like a charm for me.

Thanks nevertheless.

**Comment by jerry73204** [comment]
You can register realsense-sys to your `Cargo.toml`.

```toml
[dependencies]
realsense-sys = "0.2"
```

and call the low level C API like this.

```rust
let error = std::ptr::null_mut();
let profile = realsense_sys::rs2_config_resolve(config, pipeline, error);

// error is not automatically checked in C API, do it manually
if !error.is_null() {
    panic!("fail");
}
```

**Comment by jerry73204** [comment]
I won't blame on your choice for your design. For me if I want something *just work*, I go to Python at first. I switch to Rust if I need performance and safety, especially for large projects with million lines of code. I thank to your discovery.

**Comment by neilyoung** [comment]
Hey, Jerry, you're so kind. Thank you for spending so much time with a Rust noob like me. I was intending to try your latest suggestion, but there is something different compared to yesterday. The pose example does not compile anymore. I swear it did work yesterday:

`let poseframe = frames.pose_frame()?.unwrap();
`

```
no method named `pose_frame` found for enum `std::option::Option<realsense_rust::Frame<realsense_rust::frame_kind::Composite>>` in the current scope
```

**Comment by jerry73204** [comment]
Interesting. It compiles on my laptop (commit d8aa0913638d19bf0eeee091e07147312351b6f5).

I guess you copy and paste the `pose.rs` to run the code. If it's the case, it won't compile because I changed the function signature. I would git pull again and run by `cargo` instead of copying the file.

```sh
cargo runtig --example pose
```

I tried to simplify the API and it's now 0.5.0. The [doc](https://docs.rs/realsense-rust/0.5.0/realsense_rust/) is online if you're willing to give it a try.

**Comment by neilyoung** [comment]
Yepp. Thanks. That works. I guess I retry with your version. The way at which you implement kind of "state machine" by changing the type is super smart... I will definitely learn more about Rust...

But we are not fully through with this damned `resolve` call:

![image](https://user-images.githubusercontent.com/731020/98983350-f2f11880-2520-11eb-8345-45317df4a5e2.png)

The complain is now:

```
let config_ptr = config.into_raw();
*mut {unknown}
mismatched types

expected struct `realsense_sys::rs2_config`, found a different struct `realsense_sys::rs2_config`

note: expected raw pointer `*mut realsense_sys::rs2_config` (struct `realsense_sys::rs2_config`)
         found raw pointer `*mut realsense_sys::rs2_config` (struct `realsense_sys::rs2_config`)
note: perhaps two different versions of crate `realsense_sys` are being used?rustc(E0308)
main.rs(44, 53): expected struct `realsense_sys::rs2_config`, found a different struct `realsense_sys::rs2_config`
mismatched types


```

**Comment by jerry73204** [comment]
I looked into your code in the first post. I'm a bit curious that you use `resolve` to get the device. Perhaps we can start by pipeline, which is officially suggested ([link](https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/readme.md)). We can find the list thru [profile()](https://docs.rs/realsense-rust/0.5.0/realsense_rust/pipeline/struct.Pipeline.html#method.profile) and [device()](https://docs.rs/realsense-rust/0.5.0/realsense_rust/pipeline_profile/struct.PipelineProfile.html#method.device). The The [set_option()](https://docs.rs/realsense-rust/0.5.0/realsense_rust/sensor/struct.Sensor.html#method.get_option) on sensor is there. I know `resolve()` and `first_pose_sensor` is more convenient. I'll make it available if I have time.

**Comment by jerry73204** [comment]
Seems you're using realsense-sys 0.2. Please update to 0.3 such that your code is compatible with realsense-rust 0.5.

**Comment by neilyoung** [comment]
Problem remains, even with 0.3
```

  let profile = realsense_sys::rs2_config_resolve(config_ptr, pipe_ptr, error);
   |                                                     ^^^^^^^^^^ expected struct `realsense_sys::rs2_config`, found a different struct `realsense_sys::rs2_config`
   |


```

I will answer you in a minute regarding the start sequence I'm using in Python and why.

**Comment by neilyoung** [comment]
> I looked into your code in the first post. I'm a bit curious that you use `resolve` to get the device. Perhaps we can start by pipeline, which is officially suggested ([link](https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/readme.md)). We can find the list thru [profile()](https://docs.rs/realsense-rust/0.5.0/realsense_rust/pipeline/struct.Pipeline.html#method.profile) and [device()](https://docs.rs/realsense-rust/0.5.0/realsense_rust/pipeline_profile/struct.PipelineProfile.html#method.device). The The [set_option()](https://docs.rs/realsense-rust/0.5.0/realsense_rust/sensor/struct.Sensor.html#method.get_option) on sensor is there. I know `resolve()` and `first_pose_sensor` is more convenient. I'll make it available if I have time.

OK, there might be some noise in this code, but I hope you will be able to separate the nuts and bolts:

```
            if not self.__playing_requested:
                # Do not call cfg.enable_* after cfg.resolve has been called https://github.com/IntelRealSense/librealsense/issues/5479#issuecomment-567448946
                device = config.resolve(self.__pipeline).get_device()
                try:
                    self.__log.info("SDK: %s", rs.__version__)
                    self.__log.info("Firmware: %s", device.get_info(rs.camera_info.firmware_version))
                    self.__log.info("Serial Number: %s", device.get_info(rs.camera_info.serial_number))
                    self.__log.info("USB: %s", device.get_info(rs.camera_info.usb_type_descriptor))
                except: 
                    pass    # Info not available in current master branch (2.31.0)     
            
                # Makes only sense if not playing back
                # Get first pyrealsense2.pose_sensor in order to set options, load maps, save maps, set static node, get static node
                self.__pose_sensor = device.first_pose_sensor()
                self.__pose_sensor.set_option(rs.option.enable_map_preservation, 1)

                sensor = device.sensors[0]
                sensor.set_notifications_callback(self.__callback)

                if self.__test_startup_config("loading", lambda x: isinstance(x, dict)):
                    load_map_config = self.__start_config["loading"]
                    if load_map_config["enabled"]:
                        self.__log.debug("Loading map from '%s'", load_map_config["file_name"])
                        with open(load_map_config["file_name"], mode='rb') as map_file:
                            input_map = map_file.read()
                            self.__pose_sensor.import_localization_map(input_map)
            else:
                self.__log.debug("Enabling playback from file '%s", self.__playing_config["file_name"])
                config.enable_device_from_file(self.__playing_config["file_name"], False)

            self.__last_fix = None
            self.__last_pose = None

            # Start the pipeline
            self.__pipeline.start(config)

```

**Comment by neilyoung** [comment]
I even could drop the "try/except" sequence. 2.31.0 is long time history...

**Comment by neilyoung** [comment]
For me the important part is to get the "sensor", which allows me to load/save maps, set_/get_static_markers etc.

**Comment by jerry73204** [comment]
It compiles with realsense-sys 0.3 on my laptop. I think it's not about the version.

Note that cargo allows multiple versions of one crate co-exist together. In your case, the realsensor-rust depends on -sys 0.3, while your crate depends on -sys 0.2. Cargo will compile both versions.

It's fine in some cases. For example, you're running a large project. You don't want an old dependency of dependencies breaks your code. You can pick any version you want. It gets troubles only when you pass the type from new version to dependency's old API.

Could you show your `Cargo.toml` and rust version `rustc --version` such that I can inspect what's going on?
(I would update my toolchain by `rustup update` sometimes.)

**Comment by neilyoung** [comment]
I confirm, your sample works with `cargo run --example pose`

I separated the code from Pose into a new main and copied your Cargo.toml, so basically I' working from a new project.

Cargo.toml:

```

anyhow = "1.0"
tokio = { version  = "0.2", features = ["rt-threaded", "macros"] }
realsense-rust = { git = "https://github.com/jerry73204/realsense-rust.git" }
realsense-sys = "0.3"
```

```
rustc --version
rustc 1.47.0 (18bf6b4f0 2020-10-07)
```

**Comment by jerry73204** [comment]
See a git dependency there. I thinks it's incompatibility among git repo and -sys. Cargo will not automatically pull new commits until `cargo update`.

**Comment by neilyoung** [comment]
Oh boy, this is a crash course :) You suggested me to do the git dependency in order to benefit from "from_raw/to_raw"

Did that `cargo update`, but the problem remains, somehow.


```
error[E0308]: mismatched types
  --> src/main.rs:44:53
   |
44 |     let profile = realsense_sys::rs2_config_resolve(config_ptr, pipe_ptr, error);
   |                                                     ^^^^^^^^^^ expected struct `realsense_sys::rs2_config`, found a different struct `realsense_sys::rs2_config`
   |
   = note: expected raw pointer `*mut realsense_sys::rs2_config` (struct `realsense_sys::rs2_config`)
              found raw pointer `*mut realsense_sys::rs2_config` (struct `realsense_sys::rs2_config`)
   = note: perhaps two different versions of crate `realsense_sys` are being used?

error[E0308]: mismatched types
  --> src/main.rs:44:65
   |
44 |     let profile = realsense_sys::rs2_config_resolve(config_ptr, pipe_ptr, error);
   |                                                                 ^^^^^^^^ expected struct `realsense_sys::rs2_pipeline`, found a different struct `realsense_sys::rs2_pipeline`
   |
   = note: expected raw pointer `*mut realsense_sys::rs2_pipeline` (struct `realsense_sys::rs2_pipeline`)
              found raw pointer `*mut realsense_sys::rs2_pipeline` (struct `realsense_sys::rs2_pipeline`)
   = note: perhaps two different versions of crate `realsense_sys` are being used?

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `positions`.

To learn more, run the command again with --verbose.

```

**Comment by neilyoung** [comment]
It must be some dependency mix: If I click the symbol `rs2_config_resolve`, VSCode opens `bindings.rs` from the stored github reference, but obviously this should be resolved by the `realsense-3.0`, I guess...

**Comment by jerry73204** [comment]
It's pretty fine to use git repo. It happens to be consistent with crate.io's realsense-rust for now.

Now the master branch has `Config::resolve()` and `Device::first_xxx_sensor()` methods. Could you test them for me? The doc can be generated by the command to help you find the signature of the methods.

```sh
cargo doc --open
```

You code somewhat translates to the following. 

```rust
let pipeline = Pipeline::new()?;
let config = Config::new()?
    .enable_stream(StreamKind::Depth, 0, 640, 0, Format::Z16, 30)?
    .enable_stream(StreamKind::Color, 0, 640, 0, Format::Rgb8, 30)?;
let profile = config.resolve(&pipeline)?;

let device = profile.device()?;
let serial_number = device.serial_number()?;

let sensor = device.first_pose_sensor()?;
```

The `set_notifications_callback` is still TBD because I have to wrap my head to pass FFI callbacks to the C side. You can fallback to raw pointers to get around this.

**Comment by neilyoung** [comment]
OK, thanks for doing this. I pretty much appreciate your efforts. Great.

I changed you code a bit so that it meets my primary use case (I'm sure the other formats work as well):

 ```
    let pipeline = Pipeline::new()?;
    let config = Config::new()?
        .enable_stream(StreamKind::Pose, 0, 0, 0, Format::_6Dof, 200)?;
    let profile = config.resolve(&pipeline)?;

    let device = profile.device()?;
    let serial_number = device.serial_number()?;

    let sensor = device.first_pose_sensor()?;

```

Indeed, I was able to retrieve the serial number and there is also a "Sensor".

But I wasn't able to start the pipeline anymore:

`let mut pipeline = pipeline.start(config)?;`

Gives an error:

```
error[E0277]: the trait bound `std::option::Option<&realsense_rust::Config>: std::convert::From<realsense_rust::Config>` is not satisfied
  --> src/main.rs:44:33
   |
44 |     let mut pipeline = pipeline.start(config)?;
   |                                 ^^^^^ the trait `std::convert::From<realsense_rust::Config>` is not implemented for `std::option::Option<&realsense_rust::Config>`
   |
   = help: the following implementations were found:
             <std::option::Option<&'a T> as std::convert::From<&'a std::option::Option<T>>>
             <std::option::Option<&'a mut T> as std::convert::From<&'a mut std::option::Option<T>>>
             <std::option::Option<T> as std::convert::From<T>>
   = note: required because of the requirements on the impl of `std::convert::Into<std::option::Option<&realsense_rust::Config>>` for `realsense_rust::Config`

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0277`.

```

**Comment by neilyoung** [comment]
~~..and an attempt to get the recommended fw-version gives the usual `borrow after moved value` nonsense:~~

~~`let fw_version = device.recommended_firmware_version()?;
`~~
EDIT: Sorry, not an issue. My bad

**Comment by jerry73204** [comment]
I changed the `start()` to accept the reference `start(&config)` to prevent taking the ownership.

Plus, by calling `config.resolve(&pipeline)`, the returned profile may live longer than pipeline. I'm not sure if it is proper on the C side. Could you try this code to see what happens?

```rust
let config = Config::new();
// configure your config here
let pipeline = Pipeline::new();
let profile = config.resolve(&pipeline)?;
drop(pipeline); // explicitly drop the pipeline

// check if profile works after pipeline is dropped
let device = profile.device()?;
let sensor = device.first_post_sensor()?.unwrap();
```

**Comment by neilyoung** [comment]
Hmm. That doesn't compile at "config.resolve"

```
no method named `resolve` found for enum `std::result::Result<realsense_rust::Config, realsense_rust::Error>` in the current scope

method not found in `std::result::Result<realsense_rust::Config, realsense_rust::Error>`rustc(E0599)
main.rs(47, 22): method not found in `std::result::Result<realsense_rust::Config, realsense_rust::Error>`
no method named `resolve` found for enum `std::result::Result<realsense_rust::Config, realsense_rust::Error>` in the current scope
method not found in `std::result::Result<realsense_rust::Config, realsense_rust::Error>`rustc(E0599)


```

What am I missing?

**Comment by jerry73204** [comment]
By reading the error message, you have to unpack `Result` before actually calling `resolve`. You can see the explanation on [std doc](https://doc.rust-lang.org/std/result/). For those errors not completely related to this crate, you can try to google it to find the answer.

**Comment by neilyoung** [comment]
Yes, sorry. I should be able to find that by myself. But there is no unpack for config.

Giving up. Thanks

```
no method named `unpack` found for enum `std::result::Result<realsense_rust::Config, realsense_rust::Error>` in the current scope

method not found in `std::result::Result<realsense_rust::Config, realsense_rust::Error>`rustc(E0599)
main.rs(47, 22): method not found in `std::result::Result<realsense_rust::Config, realsense_rust::Error>`
no method named `unpack` found for enum `std::result::Result<realsense_rust::Config, realsense_rust::Error>` in the current scope
method not found in `std::result::Result<realsense_rust::Config, realsense_rust::Error>`rustc(E0599)
```

EDIT: I'm pretty confused today, there is of course an unwrap. But I begin to hate Rust. I don't really get what weird syntax is necessary to ensure memory safety. Look at Swift, they achieving the same with less obtrusive means. Reference count and done. What a mess. Unwrap here and unwrap there and & and not &... Too confusing.

EDIT2: This of course has nothing to do with this great project. But I hate to spend hours and hours fighting the compiler for stuff, which can be solved with a `try/catch` more clearly in other languages.

Thanks anyway. I will stick with Python for this project

**Comment by jerry73204** [comment]
I see your great effort. Actually I think Rust is the wrong language for your project. For one time usage application and quick development, Python or Go should be preferred.

Rust is targeted for system programming capable of writing OS kernels. There are [reasons](https://blog.plan99.net/what-s-wrong-with-exceptions-nothing-cee2ed0616) not to adopt try/catch. Rust writes `result?` sugar to simulate exception-style handling instead of `.unwrap()`. Rust also has explicit [RC](https://doc.rust-lang.org/std/rc/struct.Rc.html), unlike RC in Swift is done implicitly. RC incurs [costs](https://news.ycombinator.com/item?id=11759762) and some systems simply does not have heap to implement RC, which are not concerned in web/applications. It's not about lacking of them. Each language adopts proper design to reach their goals.

Regarding to your long journey, hope this helps finding proper choices for your project.

**Comment by neilyoung** [comment]
Well, yes. I'm not fanatic on this. I choose whatever is the lowest hanging fruit for a project. Rust is not for this, it turns out. It was an attempt. I failed, having to accept this.

BTW: After having unwrapped whatever sprang into the way, the last line didn't compile, obviously also because of an "easy to google"  error:

let sensor = device.first_post_sensor()?.unwrap();

```
no method named `first_post_sensor` found for struct `realsense_rust::Device` in the current scope

help: there is an associated function with a similar name: `first_pose_sensor`rustc(E0599)
no method named `first_post_sensor` found for struct `realsense_rust::Device` in the current scoperustc(E0599)
main.rs(52, 21): there is an associated function with a similar name

```

But maybe also some hidden Rust magic made this not to compile, who knows.

I'm frustrated like hell. OK, Friday 13th and lock down and 2020...

**Comment by neilyoung** [comment]
(Post deleted). Ah, this time it was just a typo. `post` instead of `pose`...

Not sure, if it is again an "easy to google thing", but just to finalize this:

```
error[E0382]: use of moved value: `pipeline`
   --> src/main.rs:48:6
    |
46  | let pipeline = Pipeline::new();
    |     -------- move occurs because `pipeline` has type `std::result::Result<realsense_rust::Pipeline<realsense_rust::pipeline_kind::Inactive>, realsense_rust::Error>`, which does not implement the `Copy` trait
47  | let profile = config.unwrap().resolve(&pipeline.unwrap())?;
    |                                                 -------- `pipeline` moved due to this method call
48  | drop(pipeline); // explicitly drop the pipeline
    |      ^^^^^^^^ value used here after move
    |
note: this function consumes the receiver `self` by taking ownership of it, which moves `pipeline`
   --> /Users/decades/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:970:19
    |
970 |     pub fn unwrap(self) -> T {
    |                   ^^^^

error: aborting due to previous error; 3 warnings emitted

For more information about this error, try `rustc --explain E0382`.


```

**Comment by neilyoung** [comment]
Did I ever see a more obtrusive language in my life? I admit not. It is as if your Spanish teacher is all the time standing behind you with a whip, even though this nut should be able to grasp my intention. In worst case it shouldn't suck as it does, but give some better suggestions. This is like hell...

**Comment by neilyoung** [comment]
> Actually I think Rust is the wrong language for your project.

BTW: The code (python) is ready and running flawlessly in production since months, even on a RPI 3 with 200 fps. I just wanted to give Rust a chance to see the benefits. I just see, it is an overrated, overhyped, weird language. Just for the sake of making old style C programmers happy, which managed to do a print of a text plus a newline plus some underscores (of course depending on the length of the text) in one line of code. 

I'm over this for a long time. And I don't have to prove myself to be such a crack... 👍 

But this is all not your bad. For sure. I admire your patience with such an ignorant and dumb ass like me :)


Just my $0.02
