### ISSUE TITLE
No RS devices found on Windows

### ISSUE THREAD

**Issue by tophcodes** [jerry73204/realsense-rust#17]
Hey there, originally this library wouldn't build on Windows, because `pkg_config` was not found. I traced this back to realsense-sys using `pkg-config` only for non-Windows build targets, but the alternative vcpkg wasn't used at all. I made some changes to support vcpkg, which can be seen here: https://github.com/padarom/realsense-rust/commit/3deb4a7029a50257fc680e5770cd58d9a0beaabf. I can eventually submit this as a PR once I get the examples to work.

The issue though is that I can't get rs2 to enumerate any devices. The `pose` and `reset_devices` examples both fail with `No RS devices found`. I have also tried to build with `--features buildtime-bindgen`, but it still wouldn't work. This C++ snippet using the same library version works however:

```c++
rs2::context ctx;
std::cout << "hello from librealsense - " << RS2_API_VERSION_STR << std::endl;
std::cout << "You have " << ctx.query_devices().size() << " RealSense devices connected" << std::endl;
```
```
hello from librealsense - 2.36.0
You have 1 RealSense devices connected
```

Unfortunately I don't have a lot of experience in creating lib bindings, so I have no idea how to go about debugging this. Could you give me any hints or maybe already know what the issue could be?

**Comment by tophcodes** [comment]
I figured out that this happened by only using librealsense as a static library via vcpkg. Once I reconfigured my environment to build (and search for) dynamic libraries it started working.

**Comment by jerry73204** [comment]
Can you leave your "steps by steps" here to help others on Windows? I've been years away from Windows. Your work would be appreciated. Static linking might be wanted under some circumstances, so I'm glad to have vcpkg.
