### ISSUE TITLE
Feature request: realsense 2.40.0 support

### ISSUE THREAD

**Issue by drewm1980** [jerry73204/realsense-rust#18]
2.39 is not showing up for me in intel's apt repo. Any reports yet on whether 2.40 works with realsense-rust?

**Comment by drewm1980** [comment]
I got it to build on Ubuntu 18, realsense 2.40 from intel's apt repo.

On an L515 with out of date firmware that realsense 2.40 is failing to update, I'm hitting:

Error: RealSense error: Couldn't resolve requests

Not sure yet if that's the camera, or a driver issue.

**Comment by drewm1980** [comment]
I just needed to adjust the resolutions. Now the example runs. Haven't examined the data yet.

**Comment by jerry73204** [comment]
Regarding to your issue, it's likely the resolution is not supported by the sensor, or you're plugging the device on a USB2 socket.. A relevant issue can be found on librealsense's page ([link](https://github.com/IntelRealSense/librealsense/issues/6684)).

BTW, I re-generated the bindings with librealsense 2.40.0 and now it's on master. You can import it in your `Cargo.toml` and run `cargo update` occasionally to make sure it tracks the most recent commit. The update will be in crates.io as soon as it is ready.

```toml
[dependencies]
realsense-rust = { git = "https://github.com/jerry73204/realsense-rust.git" }
```

If it still fails for you. You can try to regenerate the bindings on your own.

```toml
realsense-rust = { git = "https://github.com/jerry73204/realsense-rust.git", features = "buildtime-bindgen" }
```
