### ISSUE TITLE
Add cargo targets for all examples

### ISSUE THREAD

**Issue by rambo** [jerry73204/realsense-rust#9]
See https://github.com/jerry73204/realsense-rust/pull/8/commits/43ffd5f3457d369f94708f4735d6567c5e7794fb for how it's done.

**Comment by jerry73204** [comment]
I think it's not required since it's by default they are automatically listed on `cargo run --example`

**Comment by rambo** [comment]
Ah you are correct, I wonder why they then should be listed in Cargo.toml at all ? Maybe some other automation would like them there..
